name: domius
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5

  # UI and utilities
  provider: ^6.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/master_bedroom.jpg
    - assets/living_room.jpg     # Fixed typo: removed 'a'
    - assets/kitchen.jpg
    - assets/laundry.jpg
    - assets/logo.png
    - assets/profile.png